import org.gradle.api.attributes.plugin.GradlePluginApiVersion
import org.gradle.api.plugins.jvm.JvmTestSuite

plugins {
    id 'java-gradle-plugin'
    id 'groovy'
    id 'jvm-test-suite'
    id 'idea'
    id 'eclipse'
    id 'maven-publish'
    alias libs.plugins.licenser
    alias libs.plugins.gradleutils
    alias libs.plugins.gitversion
    alias libs.plugins.changelog
    alias libs.plugins.plugin.publish
}

final projectDisplayName = 'Forge Licenser'
final projectArtifactId = base.archivesName = 'licenser'
description = 'A simple license header manager for Gradle - Fork of org.cadixdev.licenser'
group = 'net.minecraftforge'
version = gitversion.tagOffset

println "Version: $version"

java {
    toolchain.languageVersion = JavaLanguageVersion.of(8)
    withSourcesJar()
    withJavadocJar()
}

configurations {
    // Applies the "Gradle Plugin API Version" attribute to configuration
    // This was added in Gradle 7, gives consumers useful errors if they are on an old version
    def applyGradleVersionAttribute = { Configuration configuration ->
        configuration.attributes {
            attribute(GradlePluginApiVersion.GRADLE_PLUGIN_API_VERSION_ATTRIBUTE, objects.named(GradlePluginApiVersion, libs.versions.gradle.asProvider().get()))
        }
    }

    named('runtimeElements', applyGradleVersionAttribute)
}

dependencies {
    // Gradle API
    compileOnly libs.bundles.gradle
}

license {
    header = rootProject.file('LICENSE-header.txt')
    newLine = false
    exclude '**/*.properties'
}

tasks.named('jar', Jar) {
    archiveClassifier = 'thin'
}

tasks.withType(GroovyCompile).configureEach {
    groovyOptions.optimizationOptions.indy = true
}

tasks.named('javadoc', Javadoc) {
    enabled = false
}

tasks.named('groovydoc', Groovydoc) {
    use = true
}

// javadocJar is created after evaluation, so we need to configure it here
afterEvaluate {
    tasks.named('javadocJar', Jar) {
        dependsOn tasks.named('groovydoc', Groovydoc)
        from groovydoc.destinationDir
    }
}

testing {
    def suiteSpec = { JvmTestSuite suite ->
        suite.dependencies {
            implementation.add project()
            implementation.add testLibs.gradle
            compileOnly.add libs.nulls
            implementation.bundle testLibs.bundles.spock
        }

        suite.useJUnitJupiter(testLibs.versions.junit)

        suite.targets.configureEach {
            testTask.configure {
                shouldRunAfter tasks.named('test')
            }
        }
    }

    suites.named('test', JvmTestSuite, suiteSpec)
    suites.register('functionalTest', JvmTestSuite, suiteSpec)
}

changelog {
    from '1.0'
    publishAll = false
}

gradlePlugin {
    testSourceSet sourceSets.functionalTest

    website = gitversion.url
    vcsUrl = gitversion.url + '.git'

    plugins.register('licenser') {
        id = 'net.minecraftforge.licenser'
        implementationClass = 'net.minecraftforge.licenser.Licenser'
        displayName = projectDisplayName
        description = project.description
        tags = ['license']
    }
}

publishing {
    publications.register('pluginMaven', MavenPublication) {
        artifactId = projectArtifactId
        changelog.publish it

        pom { pom ->
            name = projectDisplayName
            description = project.description

            gradleutils.pom.addRemoteDetails(pom)

            licenses {
                license gradleutils.pom.licenses.MIT
            }
        }
    }

    repositories {
        maven gradleutils.publishingForgeMaven
    }
}

idea.module { downloadSources = downloadJavadoc = true }
